#!/bin/sh



# The device's architecture

export ARCH="aarch64"



# SDK setup

export SDKVER="7.1"

export DEVROOT="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer"

export GCCROOT="/Applications/Xcode.app/Contents/Developer"

export SDKROOT="$DEVROOT/SDKs/iPhoneOS$SDKVER.sdk"


# Sanity checks

if [ ! \( -d "$DEVROOT" \) ] ; then
    echo "The iPhone SDK could not be found. Folder \"$DEVROOT\" does not exist."
    exit 1
fi



if [ ! \( -d "$SDKROOT" \) ] ; then
    echo "The iPhone SDK could not be found. Folder \"$SDKROOT\" does not exist."
    exit 1
fi

if [ ! \( -x "./configure" \) ] ; then
    echo "This script must be run in the folder containing the \"configure\" script."
    exit 1
fi



# Binaries

export CC="/usr/bin/clang"
export CPP="$CC -E"
export CXX="$CC++"
export LD="/usr/bin/ld"
export PKG_CONFIG_PATH="$SDKROOT/usr/lib/pkgconfig":"$PREFIX/lib/pkgconfig"



# Flags
export CPPFLAGS="-arch arm64 -isysroot $SDKROOT -I$PREFIX/include"
export CFLAGS="$CPPFLAGS -std=c99 -pipe -no-cpp-precomp"
export CXXFLAGS="$CPPFLAGS -I$SDKROOT/usr/include/c++/4.2.1/$ARCH -pipe -no-cpp-precomp"
export LDFLAGS="-arch arm64 -isysroot $SDKROOT -L$PREFIX/lib"



# Run configure 
# add "compat_cv_func_makedev_three_args=no to pervent crossplatform testing
./configure \
    --prefix="$PREFIX" \
    --host="$ARCH-apple-darwin" \
    --disable-static $@ 


